version: '3.8'

services:
  daemon:
    container_name: celery-daemon
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./daemon
    env_file:
      - .env
      - .env.local
    depends_on:
      - redis
      - rabbitmq
    links:
      - rabbitmq
      - redis
  gateway:
    container_name: fastapi-gateway
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./gateway
    env_file:
      - .env
      - .env.local
    ports:
      - 8081:8000
    depends_on:
      - daemon
      - redis
      - rabbitmq
    links:
      - rabbitmq
      - redis
  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3-alpine
  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
